### ISSUE TITLE
ESC protocol

### ISSUE THREAD

**Issue by zeeblaze** [kouhei1970/pico_copter#1]
Nice project btw...am also working on a Similar project...an all in one drone with rp2040 chip...and I will like to use an ESC protocol like the dshot or the oneshot...please I will like to know if you have tried controlling the motors with any on the mentioned ESC protocols...thanks in advance

**Comment by kouhei1970** [comment]
Sorry for the late reply. I do not have that experience. However, I would like to work on them.

**Comment by kouhei1970** [comment]
update
